# Generated by Django 4.2.10 on 2024-03-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date_time',
            new_name='startTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='specialist',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.therapist'),
        ),
    ]
