# Generated by Django 4.2.10 on 2024-03-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_therapist_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='client',
            new_name='name',
        ),
    ]
