# Generated by Django 4.2.10 on 2024-03-07 19:37

from django.db import migrations
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='static/images/nobody.nobody.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_menu',
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
