# Generated by Django 4.2.10 on 2024-03-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('physical activities', 'Physical Activities'), ('therapy', 'Therapy')], default='therapy', max_length=50),
        ),
    ]
