# Generated by Django 4.2.10 on 2024-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_alter_resource_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
