# Generated by Django 4.2.10 on 2024-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_resource_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="clickable_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
