# Generated by Django 4.2.10 on 2024-03-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_resource_clickable_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="video_url",
        ),
    ]
